language: java

os: osx
# os :


addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


install:
  - npm install npm@latest -g
  - npm install coveralls
  - npm install @compodoc/compodoc